#include "MediaPipeShoulderRollbackDiagnostics.h"

FString FMediaPipeShoulderRollbackDiagnostics::FormatTraceLog(
	const FMediaPipeShoulderRollbackTraceFormatInput& Input)
{
	return FString::Printf(
		TEXT("mp.MediaPipeShoulderRollbackTrace: actor=%s side=%s upperBehind=%d wristBehind=%d crossedBehind=%d targetSnap=%d clampHit=%d guardApplied=%d guardBlend=%.2f upperForwardDot=%.2f lowerForwardDot=%.2f wristForwardDot=%.2f prevUpperForwardDot=%.2f backThreshold=%.2f upperTargetStepDeg=%.1f lowerTargetStepDeg=%.1f upperAppliedStepDeg=%.1f lowerAppliedStepDeg=%.1f armMaxStepDeg=%.1f upperTargetFromRefDeg=%.1f lowerTargetFromRefDeg=%.1f elbowPlaneOutwardDot=%.2f stablePole=%d elbowPlaneRoll=%d armIK=%d questForceArmIK=%d legs=%d legIK=%d pelvisTranslation=%d clavicles=%d torsoBasis=%d shoulderReliability=%.2f elbowReliability=%.2f wristReliability=%.2f shoulderForwardCm=%.1f elbowForwardCm=%.1f wristForwardCm=%.1f shoulder=%s elbow=%s wrist=%s forward=%s up=%s shoulderRight=%s hipRight=%s"),
		*Input.TargetActorName.ToString(),
		Input.bIsLeft ? TEXT("L") : TEXT("R"),
		Input.bUpperBehind ? 1 : 0,
		Input.bWristBehind ? 1 : 0,
		Input.bCrossedBehind ? 1 : 0,
		Input.bTargetSnap ? 1 : 0,
		Input.bClampHit ? 1 : 0,
		Input.bGuardApplied ? 1 : 0,
		Input.GuardBlend,
		Input.UpperForwardDot,
		Input.LowerForwardDot,
		Input.WristForwardDot,
		Input.PreviousUpperForwardDot,
		Input.BackThreshold,
		Input.UpperTargetStepDeg,
		Input.LowerTargetStepDeg,
		Input.UpperAppliedStepDeg,
		Input.LowerAppliedStepDeg,
		Input.ArmMaxStepDeg,
		Input.UpperTargetFromRefDeg,
		Input.LowerTargetFromRefDeg,
		Input.ElbowPlaneOutwardDot,
		Input.bStablePole ? 1 : 0,
		Input.bElbowPlaneRoll ? 1 : 0,
		Input.bArmIK ? 1 : 0,
		Input.bQuestForceArmIK ? 1 : 0,
		Input.bLegs ? 1 : 0,
		Input.bLegIK ? 1 : 0,
		Input.bPelvisTranslation ? 1 : 0,
		Input.bClavicles ? 1 : 0,
		Input.bTorsoBasis ? 1 : 0,
		Input.ShoulderReliability,
		Input.ElbowReliability,
		Input.WristReliability,
		Input.ShoulderForwardCm,
		Input.ElbowForwardCm,
		Input.WristForwardCm,
		*Input.ShoulderWorld.ToCompactString(),
		*Input.ElbowWorld.ToCompactString(),
		*Input.WristWorld.ToCompactString(),
		*Input.ForwardWorld.ToCompactString(),
		*Input.UpWorld.ToCompactString(),
		*Input.ShoulderRightWorld.ToCompactString(),
		*Input.HipRightWorld.ToCompactString());
}
